# Generated by Django 3.0.8 on 2020-07-31 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeCooked', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vendor',
            new_name='Kitchn',
        ),
    ]
