# Generated by Django 3.0.8 on 2020-07-30 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeCooked', '0002_auto_20200730_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='description',
            field=models.CharField(max_length=300),
        ),
    ]
